# ==========================================
# BUILD STAGE
# ==========================================

FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN mvn clean package -DskipTests


# ==========================================
# TOMCAT STAGE
# ==========================================

FROM tomcat:10.1-jre25-temurin-noble

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build \
     /app/target/UserManagement.war \
     /usr/local/tomcat/webapps/ROOT.war

# Vercel will provide PORT.
# If PORT is not provided, use 8080.
ENV PORT=8080

EXPOSE 8080

CMD ["sh", "-c", "sed -i \"s/port=\\\"8080\\\"/port=\\\"${PORT}\\\"/\" /usr/local/tomcat/conf/server.xml && catalina.sh run"]